learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Show all topics
    path('topics/', views.topics, name='topics'),

    # Detailed page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for adding a new entry
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),

    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

    # Page for deleting an entry
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),

    # Login page
]

users/urls.py
"""Defines URL patterns for users"""

from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [

    # Login Page
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # Log out page
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Registration page
    path('registration/', views.register, name='register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """ A topic the user is learning about."""
    objects = None
    text = models.CharField(max_length=200)  # Recording the title of the Topic with a max length of 200 characters
    date_added = models.DateTimeField(auto_now_add=True)  # Recording the date and time that a topic was created
    # automatically using auto_now_add=True
    owner = models.ForeignKey(User, on_delete=models.CASCADE)  # Adds the owner field which creates a foreignkey
    # relationship to the Topic class to the User model. If a USER is deleted so are the Topics and Entries they created

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        # Overriding Django's widgets and setting the column length from default 40 to 80

learning_logs/views.py
from django.shortcuts import render
# from django.template import loader
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from learning_logs.models import Topic, Entry
from learning_logs.forms import TopicForm, EntryForm


# Create your views here.

def check_topic_owner(owner, user):
    """Function to check the registered user versus the user that created the given topic."""
    if owner != user:
        raise Http404
    return


def index(request):
    """The Home Page for Anime Ratings"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Shows us all the topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all of its entries."""
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic.owner, request.user)  # Make sure the topic belongs to the current user

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':  # No data submitted; Create a blank form.
        form = TopicForm()
    else:  # POST data submitted; process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse_lazy('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a selected topic"""
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic.owner, request.user)

    if request.method != 'POST':  # No data submitted; Create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse_lazy('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic.owner, request.user)  # Make sure the topic belongs to the current user

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    """Delete a selected/existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # entry.delete()

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        entry.delete()
        return HttpResponseRedirect(reverse_lazy('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/delete_entry.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% load static%}

<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Your Diary</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    <body>
<!---->
        <!-- Static navbar-->
        <nav class="navbar navbar-default navbar-static-top" style="background-color: #8cffe6;">
            <div class="container">

                <a class="navbar-brand"><img src="{% static 'learning_logs/logo.png' %}" width="35" height="30"
                                             class="align-baseline" alt="Darrell_Logo"> </a>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                    </button>

                      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Dear, Diary</a>

                </div>

                <div id="navbar" class="navbar-collapse collapse align-top">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right align-top">
                        {% if user.is_authenticated %}
                            <li><a>Hello, {{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}">Log Out</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">Register</a> </li>
                            <li><a href="{% url 'users:login' %}">Login</a> </li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse-->

            </div>
        </nav>

        <div class="container">

            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </div>        <!-- /container -->

    </body>
</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends "learning_logs/base.html" %}

{% block title %}Edit Content Entry{% endblock title %}
{% block header %}Delete Entry Page{% endblock header %}
{% block content%}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>

    <h2>Do you want to delete this entry?</h2>

    <form action="{% url 'learning_logs:delete_entry' entry.id %}" method="get">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="Delete" formmethod="post">Yes?</button>

        <a href="{% url 'learning_logs:topic' topic.id %}">
            <input type="button" value="No." />
        </a>

    </form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block title %}Edit Content Entry{% endblock title %}
{% block header %}Edit Entry Page{% endblock header %}
{% block content%}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>

    <p>Edit entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save Changes</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="jumbotron text-center">
        <h2>Tell your diary about your day!</h2>
    </div>
{% endblock header %}

{% block content %}
    <h3>
        <a href="{% url 'users:register' %}">Register an account</a> to document how you feel
        about any and everything that is going on with you.
    </h3>

    <h3>
        Whenever you feel the need to write down what's going on in your life, talk to your diary.
        Have faith that your information is safe and secure with us.
    </h3>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block title %}Content Entry{% endblock title %}
{% block header %}Entry Page{% endblock header %}
{% block content%}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>

    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add an Entry</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content%}

    <form action="{% url 'learning_logs:new_topic' %}" method="post" class = "form">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add Topic</button>
        {% endbuttons %}

    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <div class="text-center">
        <h2>{{ topic }}</h2>
    </div>
{% endblock header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a New Topic Entry!</a>
    </p>
        {% for entry in entries %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>
                        {{ entry.date_added|date:'M d, Y H:i' }}
                        <small>
                            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit </a> -
                         <a href="{% url 'learning_logs:delete_entry' entry.id %}"> Delete</a>
                        </small>
                    </h4>
                </div>
                <div class="panel-body">
                    {{ entry.text|linebreaks }}
                </div>
            </div>
    {% empty %}
        There are no entries for this topic yet. Be the first to create one!
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="text-center">
        <h2>Topics Page</h2>
    </div>
{% endblock header %}

{% block content%}
    <h4><a href="{% url 'learning_logs:new_topic' %}">Add a new topic here!</a></h4>

    {% for topic in topics %}
        <div class="panel panel-default text-center text-align">
            <div class="panel-heading">
            <h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </h3>
            </div>
        </div>
        {% empty %}
            You haven't added any topics yet!
        {% endfor %}


{% endblock content %}